user backend_procel_telemetry
topic read procel/telemetry/v1/#
topic read $SYS/#

user sensor_producer_001
topic write procel/telemetry/v1/producer_001/#

user sensor_producer_002
topic write procel/telemetry/v1/producer_002/#
