persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true

allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl.conf

listener 8883 0.0.0.0
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key

max_connections 1000
message_size_limit 0
